export const FIND_OR_CREATE_USER_REQUESTED = 'FIND_OR_CREATE_USER_REQUESTED';
export const FIND_OR_CREATE_USER_PENDING = 'FIND_OR_CREATE_USER_PENDING';
export const FIND_OR_CREATE_USER_SUCCESS = 'FIND_OR_CREATE_USER_SUCCESS';
export const FIND_OR_CREATE_USER_FAILED = 'FIND_OR_CREATE_USER_FAILED';
