export const SAVE_NEW_DIAGRAM_BY_PROJECT_REQUESTED = 'SAVE_NEW_DIAGRAM_BY_PROJECT_REQUESTED';
export const SAVE_NEW_DIAGRAM_REQUESTED = 'SAVE_NEW_DIAGRAM_REQUESTED';
export const SAVE_NEW_DIAGRAM_PENDING = 'SAVE_NEW_DIAGRAM_PENDING';
export const SAVE_NEW_DIAGRAM_SUCCESS = 'SAVE_NEW_DIAGRAM_SUCCESS';
export const SAVE_NEW_DIAGRAM_FAILED = 'SAVE_NEW_DIAGRAM_FAILED';

export const SAVE_DIAGRAM_REQUESTED = 'SAVE_DIAGRAM_REQUESTED';
export const SAVE_DIAGRAM_PENDING = 'SAVE_DIAGRAM_PENDING';
export const SAVE_DIAGRAM_SUCCESS = 'SAVE_DIAGRAM_SUCCESS';
export const SAVE_DIAGRAM_FAILED = 'SAVE_DIAGRAM_FAILED';

export const DIAGRAMS_REQUESTED = 'DIAGRAMS_REQUESTED';
export const DIAGRAMS_PENDING = 'DIAGRAMS_PENDING';
export const DIAGRAMS_RECEIVED = 'DIAGRAMS_RECEIVED';
export const DIAGRAMS_REQUEST_FAILED = 'DIAGRAMS_REQUEST_FAILED';

export const UPDATE_DIAGRAM_REQUESTED = 'UPDATE_DIAGRAM_REQUESTED';
export const UPDATE_DIAGRAM_NAME_REQUESTED = 'UPDATE_DIAGRAM_NAME_REQUESTED';
export const UPDATE_DIAGRAM_PENDING = 'UPDATE_DIAGRAM_PENDING';
export const UPDATE_DIAGRAM_SUCCESS = 'UPDATE_DIAGRAM_SUCCESS';
export const UPDATE_DIAGRAM_FAILED = 'UPDATE_DIAGRAM_FAILED';

export const DELETE_DIAGRAM_BY_PROJECT_REQUESTED = 'DELETE_DIAGRAM_BY_PROJECT_REQUESTED';
export const DELETE_DIAGRAM_REQUESTED = 'DELETE_DIAGRAM_REQUESTED';
export const DELETE_DIAGRAM_PENDING = 'DELETE_DIAGRAM_PENDING';
export const DELETE_DIAGRAM_SUCCESS = 'DELETE_DIAGRAM_SUCCESS';
export const DELETE_DIAGRAM_FAILED = 'DELETE_DIAGRAM_FAILED';

export const SET_DIAGRAMS = 'SET_DIAGRAMS';
