export const SET_GUIDELINE_POSITION_0 = 'SET_GUIDELINE_POSITION_0';
export const SET_GUIDELINE_ACTIVE = 'SET_GUIDELINE_ACTIVE';
export const SET_GUIDELINE_INACTIVE = 'SET_GUIDELINE_INACTIVE';
export const SET_GUIDELINE_PROPERTIES = 'SET_GUIDELINE_PROPERTIES';
export const SET_DEFAULT_GUIDELINE_STATE = 'SET_DEFAULT_GUIDELINE_STATE';
