export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const UPDATE_SIDEBAR_DATA = 'UPDATE_SIDEBAR_DATA';
export const SELECT_ITEM = 'SELECT_ITEM';
export const UNSELECT_ITEM = 'UNSELECT_ITEM';
export const SELECT_SIDEBAR_OPTION = 'SELECT_SIDEBAR_OPTION';
export const UNSELECT_SIDEBAR_OPTION = 'UNSELECT_SIDEBAR_OPTION';

export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const DEL_CURRENT_ITEM = 'DEL_CURRENT_ITEM';
export const CHANGE_LAST_ITEM = 'CHANGE_LAST_ITEM';
export const CLEAN_ITEMS = 'CLEAN_ITEMS';

// Canvas
export const SET_ITEM_TYPE = 'SET_ITEM_TYPE';
export const TOGGLE_NOTETB_STATUS = 'TOGGLE_NOTETB_STATUS';
export const SET_NOTETB_ACTIVE = 'SET_NOTETB_ACTIVE';
export const SET_NOTETB_INACTIVE = 'SET_NOTETB_INACTIVE';

// Navbar
export const CHANGE_ACTIVE_NAVITEM = 'CHANGE_ACTIVE_NAVITEM';
export const CHANGE_NAV_MENU_ITEM_ID = 'CHANGE_NAV_MENU_ITEM_ID';
export const SET_MENU_ACTIVE = 'SET_MENU_ACTIVE';
export const SET_MENU_INACTIVE = 'SET_MENU_INACTIVE';

// Modal
export const SET_MODAL = 'SET_MODAL';
export const APPROVE_MODAL = 'APPROVE_MODAL';
export const DISPOSE_MODAL = 'DISPOSE_MODAL';

// Panel
export const SET_INDEX_PANEL = 'SET_INDEX_PANEL';

// General
export const RESET_UI = 'RESET_UI';
