export {
  MENU_TEMPLATES,
  MENU_DIAGRAMS,
  MENU_SAVE_AS_TEMPLATE,
  MENU_SAVE_AS_JPG,
} from './menu';
export { MODAL_SIMPLE, MODAL_INPUT } from './modal';
export {
  NAV_MY_FILES,
  NAV_CLOSE_WORK,
  NAV_NEW_DIAGRAM,
  NAV_OPEN_FILE,
  NAV_SAVE_DIAGRAM,
  NAV_SAVE_AS,
  NAV_CONTROL,
  NAV_BOUNDARY,
  NAV_ENTITY,
  NAV_ACTOR,
  NAV_ASSOCIATION,
  NAV_ASSOCIATION_WITH,
  NAV_EXTRA_LOGOUT,
} from './navbar';
export {
  MAIN_PANEL_INDEX,
  PROJECTS_PANEL_INDEX,
  TEMPLATES_PANEL_INDEX,
  DIAGRAMS_PANEL_INDEX,
  PROJECTS_PANEL_ACTS_SAVEDIAGRAM,
} from './panel';
export { FINPUT_MIN_WIDTH, FAB_NOTE_MAX_LEN } from './ui';
