export const MAIN_PANEL_INDEX = 0;
export const PROJECTS_PANEL_INDEX = 1;
export const TEMPLATES_PANEL_INDEX = 2;
export const DIAGRAMS_PANEL_INDEX = 3;

export const PROJECTS_PANEL_ACTS_SAVEDIAGRAM = 'PROJECTS_PANEL_ACTS_SAVEDIAGRAM';
