export const SET_TDIAGRAMS = 'SET_TDIAGRAMS';

export const TDIAGRAMS_REQUESTED = 'TDIAGRAMS_REQUESTED';
export const TDIAGRAMS_PENDING = 'TDIAGRAMS_PENDING';
export const TDIAGRAMS_RECEIVED = 'TDIAGRAMS_RECEIVED';
export const TDIAGRAMS_REQUEST_FAILED = 'TDIAGRAMS_REQUEST_FAILED';

export const SAVE_TDIAGRAM_REQUESTED = 'SAVE_TDIAGRAM_REQUESTED';
export const CREATE_TDIAGRAM_REQUESTED = 'CREATE_TDIAGRAM_REQUESTED';
export const CREATE_TDIAGRAM_PENDING = 'CREATE_TDIAGRAM_PENDING';
export const CREATE_TDIAGRAM_SUCCESS = 'CREATE_TDIAGRAM_SUCCESS';
export const CREATE_TDIAGRAM_FAILED = 'CREATE_TDIAGRAM_FAILED';

export const UPDATE_TDIAGRAM_REQUESTED = 'UPDATE_TDIAGRAM_REQUESTED';
export const UPDATE_TDIAGRAM_PENDING = 'UPDATE_TDIAGRAM_PENDING';
export const UPDATE_TDIAGRAM_SUCCESS = 'UPDATE_TDIAGRAM_SUCCESS';
export const UPDATE_TDIAGRAM_FAILED = 'UPDATE_TDIAGRAM_FAILED';

export const REMOVE_TDIAGRAM_REQUESTED = 'REMOVE_TDIAGRAM_REQUESTED';
export const REMOVE_TDIAGRAM_PENDING = 'REMOVE_TDIAGRAM_PENDING';
export const REMOVE_TDIAGRAM_SUCCESS = 'REMOVE_TDIAGRAM_SUCCESS';
export const REMOVE_TDIAGRAM_FAILED = 'REMOVE_TDIAGRAM_FAILED';
