export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_PROJECT = 'SET_PROJECT';
export const LOCAL_CREATE_PROJECT = 'LOCAL_CREATE_PROJECT';
export const LOCAL_UPDATE_PROJECT = 'LOCAL_UPDATE_PROJECT';
export const LOCAL_REMOVE_PROJECT = 'LOCAL_REMOVE_PROJECT';
export const LOCAL_CREATE_DIAGRAM_IN_PROJECT = 'LOCAL_CREATE_DIAGRAM_IN_PROJECT';
export const LOCAL_REMOVE_DIAGRAM_IN_PROJECT = 'LOCAL_REMOVE_DIAGRAM_IN_PROJECT';

export const PROJECTS_REQUESTED = 'PROJECTS_REQUESTED';
export const PROJECTS_PENDING = 'PROJECTS_PENDING';
export const PROJECTS_RECEIVED = 'PROJECTS_RECEIVED';
export const PROJECTS_REQUEST_FAILED = 'PROJECTS_REQUEST_FAILED';

export const PROJECT_REQUESTED = 'PROJECT_REQUESTED';
export const PROJECT_PENDING = 'PROJECT_PENDING';
export const PROJECT_RECEIVED = 'PROJECT_RECEIVED';
export const PROJECT_REQUEST_FAILED = 'PROJECT_REQUEST_FAILED';

export const CREATE_PROJECT_REQUESTED = 'CREATE_PROJECT_REQUESTED';
export const CREATE_PROJECT_PENDING = 'CREATE_PROJECT_PENDING';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED';

export const UPDATE_PROJECT_REQUESTED = 'UPDATE_PROJECT_REQUESTED';
export const UPDATE_PROJECT_PENDING = 'UPDATE_PROJECT_PENDING';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILED = 'UPDATE_PROJECT_FAILED';

export const REMOVE_PROJECT_REQUESTED = 'REMOVE_PROJECT_REQUESTED';
export const REMOVE_PROJECT_PENDING = 'REMOVE_PROJECT_PENDING';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';
export const REMOVE_PROJECT_FAILED = 'REMOVE_PROJECT_FAILED';

export const ADD_MEMBER_REQUESTED = 'ADD_MEMBER_REQUESTED';
export const ADD_MEMBER_PENDING = 'ADD_MEMBER_PENDING';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILED = 'ADD_MEMBER_FAILED';

export const REMOVE_MEMBER_REQUESTED = 'REMOVE_MEMBER_REQUESTED';
export const REMOVE_MEMBER_PENDING = 'REMOVE_MEMBER_PENDING';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_FAILED = 'REMOVE_MEMBER_FAILED';
